# App Engine runtime configuration
runtime: php72

# Defaults to "serve index.php" and "serve public/index.php". Can be used to
# serve a custom PHP front controller (e.g. "serve backend/index.php") or to
# run a long-running PHP script as a worker process (e.g. "php worker.php").
entrypoint: serve wordpress/gae-app.php

# Defines static handlers to serve WordPress assets
handlers:
  - url: /(.*\.(htm|html|css|js))
    static_files: wordpress/\1
    upload: wordpress/.*\.(htm|html|css|js)$
    secure: always

  - url: /wp-content/(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))
    static_files: wordpress/wp-content/\1
    upload: wordpress/wp-content/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
    secure: always

  - url: /(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))
    static_files: wordpress/\1
    upload: wordpress/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
    secure: always

  - url: /wp-includes/images/media/(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))
    static_files: wordpress/wp-includes/images/media/\1
    upload: wordpress/wp-includes/images/media/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
    secure: always
