name: Publish on Gcloud
on:
  release:
    types: [published]

jobs:
  build:
    name: deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/checkout@v1
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "270.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: dependencies
        run: npm install
      - name: deploy
        run: gcloud app deploy app.yaml cron.yaml --project=${{ secrets.GCP_ID_PROJECT }}
